apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gin-api-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      bindings:
        - ref: github-binding
      template:
        ref: gin-api-template
