apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: revision
      value: $(body.head_commit.id)
    - name: url
      value: $(body.repository.clone_url)
