version: 0.2

env:
  variables:
    GO111MODULE: "on"
    CGO_ENABLED: "0"
    GOOS: "linux"
    GOARCH: "amd64"
  # Uncomment if you want environment variables from Secrets Manager
  # secrets-manager:
  #   MY_SECRET: my-secret-name:my-key

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
      - go mod download

  pre_build:
    commands:
      - echo "Running tests..."
      - go test ./... -v

  build:
    commands:
      - echo "Building application..."
      - go build -o app main.go

  post_build:
    commands:
      - echo "Packaging build artifacts..."
      - mkdir -p build
      - mv app build/
      - echo "Build completed on `date`"

artifacts:
  files:
    - build/**/*
    - appspec.yml         # if you’re using CodeDeploy
    - scripts/**/*
  discard-paths: no
